var lcdWidth = 320;
var lcdHeight = 240


function CharToTICalcChar(character){
    switch(character){
        case "ItalicN": return "01";
        case "MathU": return "02";
        case "MathV": return "03";
        case "MathW": return "04";
        case "TriangleRight": return "05";
        case "FatArrowUp": return "06";
        case "FatArrowDown": return "07";
        case "Integral": return "08";
        case "MathX": return "09";
        case "EmptySquare": return "0A";
        case "Positive": return "0B";
        case "FloatingDot": return "0C";
        case "LowT": return "0D";
        case "Cubed": return "0E";
        case "FatF": return "0F";
        case "SquareRoot": return "10";
        case "Inverse": return "11";
        case "Squared": return "12";
        case "Angle": return "13";
        case "Degree": return "14";
        case "HighR": return "15";
        case "HighT": return "16";
        case "LessThanOrEqualTo": return "17";
        case "NotEqualTo": return "18";
        case "GreaterThanOrEqualTo": return "19";
        case "Negetive": return "1A";
        case "Time10ToThePowerOf": return "1B";
        case "ArrowRight": return "1C";
        case "10": return "1D";
        case "ArrowUp": return "1E";
        case "ArrowDown": return "1F";
        case " ": return "20";
        case "!": return "21";
        case "\"": return "22";
        case "#": return "23";
        case "$": return "24";
        case "%": return "25";
        case "&": return "26";
        case "\'": return "27";
        case "(": return "28";
        case ")": return "29";
        case "*": return "2A";
        case "+": return "2B";
        case ",": return "2C";
        case "-": return "2D";
        case ".": return "2E";
        case "/": return "2F";
        case "0": return "30";
        case "1": return "31";
        case "2": return "32";
        case "3": return "33";
        case "4": return "34";
        case "5": return "35";
        case "6": return "36";
        case "7": return "37";
        case "8": return "38";
        case "9": return "39";
        case ":": return "3A";
        case "SemiColon": return "3B";
        case "<": return "3C";
        case "=": return "3D";
        case ">": return "3E";
        case "?": return "3F";
        case "@": return "40";
        case "A": return "41";
        case "B": return "42";
        case "C": return "43";
        case "D": return "44";
        case "E": return "45";
        case "F": return "46";
        case "G": return "47";
        case "H": return "48";
        case "I": return "49";
        case "J": return "4A";
        case "K": return "4B";
        case "L": return "4C";
        case "M": return "4D";
        case "N": return "4E";
        case "O": return "4F";
        case "P": return "50";
        case "Q": return "51";
        case "R": return "52";
        case "S": return "53";
        case "T": return "54";
        case "U": return "55";
        case "V": return "56";
        case "W": return "57";
        case "X": return "58";
        case "Y": return "59";
        case "Z": return "5A";
        case "Theta": return "5B";
        case "BackSlash": return "5C";
        case "]": return "5D";
        case "^": return "5E";
        case "_": return "5F";
        case "\`": return "60";
        case "a": return "61";
        case "b": return "62";
        case "c": return "63";
        case "d": return "64";
        case "e": return "65";
        case "f": return "66";
        case "g": return "67";
        case "h": return "68";
        case "i": return "69";
        case "j": return "6A";
        case "k": return "6B";
        case "l": return "6C";
        case "m": return "6D";
        case "n": return "6E";
        case "o": return "6F";
        case "p": return "70";
        case "q": return "71";
        case "r": return "72";
        case "s": return "73";
        case "t": return "74";
        case "u": return "75";
        case "v": return "76";
        case "w": return "77";
        case "x": return "78";
        case "y": return "79";
        case "z": return "7A";
        case "{": return "7B";
        case "|": return "7C";
        case "}": return "7D";
        case "~": return "7E";
        case "InvertedEqual": return "7F";
        case "Small0": return "80";
        case "Small1": return "81";
        case "Small2": return "82";
        case "Small3": return "83";
        case "Small4": return "84";
        case "Small5": return "85";
        case "Small6": return "86";
        case "Small7": return "87";
        case "Small8": return "88";
        case "Small9": return "89";
        case "AForward": return "8A";
        case "ABack": return "8B";
        case "AHat": return "8C";
        case "A2Dots": return "8D";
        case "aForward": return "8E";
        case "aBack": return "8F";
        case "aHat": return "90";
        case "a2Dots": return "91";
        case "EForward": return "92";
        case "EBack": return "93";
        case "EHat": return "94";
        case "E2Dots": return "95";
        case "eForward": return "96";
        case "eBack": return "97";
        case "eHat": return "98";
        case "e2Dots": return "99";
        case "IForward": return "9A";
        case "IBack": return "9B";
        case "IHat": return "9C";
        case "I2Dots": return "9D";
        case "iForward": return "9E";
        case "iBack": return "9F";
        case "iHat": return "A0";
        case "i2Dots": return "A1";
        case "OForward": return "A2";
        case "OBack": return "A3";
        case "OHat": return "A4";
        case "O2Dots": return "A5";
        case "oForward": return "A6";
        case "oBack": return "A7";
        case "oHat": return "A8";
        case "o2Dots": return "A9";
        case "UForward": return "AA";
        case "UBack": return "AB";
        case "UHat": return "AC";
        case "U2Dots": return "AD";
        case "uForward": return "AE";
        case "uBack": return "AF";
        case "uHat": return "B0";
        case "u2Dots": return "B1";
        case "CString": return "B2";
        case "cString": return "B3";
        case "N~": return "B4";
        case "n~": return "B5";
        case "SuperForward": return "B6";
        case "SuperBack": return "B7";
        case "Super2Dots": return "B8";
        case "UpsideDown?": return "B9";
        case "UpsideDown!": return "BA";
        case "Alpha": return "BB";
        case "Beta": return "BC";
        case "Gamma": return "BD";
        case "SmallTriangle": return "BE";
        case "Delta": return "BF";
        case "Epsilon": return "C0";
        case "[": return "C1";
        case "Lambda": return "C2";
        case "Mu": return "C3";
        case "Pi": return "C4";
        case "Rho": return "C5";
        case "Sigma": return "C6";
        case "oWithRightFlag": return "C7";
        case "Tau": return "C8";
        case "Phi": return "C9";
        case "Omega": return "CA";
        case "XBar": return "CB";
        case "YBar": return "CC";
        case "SuperX": return "CD";
        case "...": return "CE";
        case "TriangleLeft": return "CF";
        case "FilledSquare": return "D0";
        case "DiagonalToUpperRight": return "D1";
        case "Dash": return "D2";
        case "Super2": return "D3";
        case "SuperCircle": return "D4";
        case "Super3": return "D5";
        case "NewLine": return "D6";
        case "Colon": return "D7";
        case "imaginary": return "D8";
        case "pHat": return "D9";
        case "ShakyX": return "DA";
        case "LargeF": return "DB";
        case "euler": return "DC";
        case "SmallL": return "DD";
        case "FatN": return "DE";
        case "Double)": return "DF";
        case "FatArrowRight": return "E0";
        case "Cursor": return "E1";
        case "Shift": return "E2";
        case "AlphaSelect": return "E3";
        case "Insert": return "E4";
        case "InvertedShift": return "E5";
        case "InvertedAlpha": return "E6";
        case "InvetedAlphaSelect": return "E7";
        case "DiagonalToLowerRight": return "E8";
        case "FatDiagonalToLowerRight": return "E9";
        case "TopTriangle": return "EA";
        case "BottomTriangle": return "EB";
        case "HalfKey": return "EC";
        case "ThirdKey": return "ED";
        case "DottedDiagonalToLowerRight": return "EE";
        case "BoldArrowUp": return "EF";
        case "BoldArrowDown": return "F0";
        case "GridCursor": return "F1";
        case "Super4": return "F2";
        case "UpperBoldArrowUp": return "F3";
        case "UpperBeta": return "F4";
        case "Cup": return "F5";
        case "FatDiagonalToUpperRight": return "F6";
        case "OutlineCursor": return "F7";
        case "BlockyDiagionalToLowerRight": return "F8";
        case "Pixel": return "F9";
        default: return "00";
    }
}

function SystemCallToHex(systCall) {
    switch (systCall) {
        case "OSSize":return "020104";
        case "BootOS":return "020108";
        case "InterruptHandler":return "02010C";
        case "Rst10Handler":return "020110";
        case "Rst18Handler":return "020114";
        case "Rst20Handler":return "020118";
        case "Rst28Handler":return "02011C";
        case "Rst30Handler":return "020120";
        case "JErrorNo":return "02012C";
        case "CallFrontHook":return "020130";
        case "CallLocalizeHook":return "020134";
        case "LoadHLInd_s":return "020138";
        case "CpHLDE":return "02013C";
        case "DivHLBy10_s":return "020140";
        case "DivHLByA_s":return "020144";
        case "KbdScan":return "020148";
        case "GetCSC":return "02014C";
        case "CoorMon":return "020150";
        case "Mon":return "020154";
        case "MonForceKey":return "020158";
        case "SendKPress":return "02015C";
        case "JForceCmdNoChar":return "020160";
        case "JForceCmd":return "020164";
        case "SystErrHandler":return "020168";
        case "NewContext":return "02016C";
        case "NewContext0":return "020170";
        case "PPutAwayPrompt":return "020174";
        case "PPutAway":return "020178";
        case "PutAway":return "02017C";
        case "SizeWind":return "020180";
        case "ErrorEP":return "020184";
        case "CallMain":return "020188";
        case "MonErrHand":return "02018C";
        case "AppInit":return "020190";
        case "Initialize":return "020194";
        case "Min":return "020198";
        case "Max":return "02019C";
        case "AbsO1PAbsO2":return "0201A0";
        case "Intgr":return "0201A4";
        case "TRunc":return "0201A8";
        case "InvSub":return "0201AC";
        case "Times2":return "0201B0";
        case "Plus1":return "0201B4";
        case "Minus1":return "0201B8";
        case "FPSub":return "0201BC";
        case "FPAdd":return "0201C0";
        case "DToR":return "0201C4";
        case "RToD":return "0201C8";
        case "Cube":return "0201CC";
        case "TimesPT5":return "0201D0";
        case "FPSquare":return "0201D4";
        case "FPMult":return "0201D8";
        case "LJRnd":return "0201DC";
        case "InvOP1Sc":return "0201E0";
        case "InvOP1S":return "0201E4";
        case "InvOP2S":return "0201E8";

        case "DispHL_s": return "0207BC";
        case "PutS": return "0207C0";
        case "PutPSB": return "0207C4";
        case "PutPS": return "0207C8";
        case "WPutPS": return "0207CC";
        case "PutBuff": return "0207D0";
        case "PutBuff1": return "0207D4";
        case "WPutC": return "0207D8";
        case "WPutS": return "0207DC";
        case "WPutSEOL": return "0207E0";
        case "WDispEOL": return "0207E4";
        case "WHomeUp": return "0207E8";
        case "SetNumWindow": return "0207EC";
        case "NewLine": return "0207F0";
        case "MoveDown": return "0207F4";
        case "ScrollUp": return "0207F8";
        case "ShrinkWindow": return "0207FC";
        case "MoveUp": return "020800";
        case "ScrollDown": return "020804";
        case "ClrLCDFull": return "020808";
        case "ClrLCD": return "02080C";
        case "ClrScreenFull": return "020810";
        case "ClrScreen": return "020814";
        case "ClrTextShd": return "020818";
        case "ClrWindow": return "02081C";
        case "EraseEOL": return "020820";
        case "EraseEOW": return "020824";
        case "HomeUp": return "020828";


        case "":return "";
        default:
            return "onknUn";
    }
}